version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn api.main:api --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/api
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0